# https://travis-ci.org/jnsebgosselin/WHAT

language: python
python:
  - "3.4"

install:
  - sudo apt-get install python3-pyside
  - pip install coveralls

script: 
  - vpytest

after_success: 
  - coveralls
