# https://ci.appveyor.com/project/jnsebgosselin/gwhat

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

branches:
  only:
    - master

environment:
  global:
    GWHAT_VERSION: "gwhat_0.4.0.dev0"

  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

platform:
  -x64

skip_branch_with_pr: true

install:
  # Cancel older builds for the same PR.
  # Credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
      
  # Setup SYS PATH.
  - set "PATH=%PYTHON%;%PYTHON%/Scripts;%PYTHON%/Library/bin;%PATH%"

  # Setup Conda.
  - conda config --set always_yes yes
  - conda config --set auto_update_conda no
  - conda install -c conda-forge -c defaults pyqt5 xlsxwriter xlrd xlwt `
    cython scipy matplotlib requests h5py qtawesome pytest pytest-mock `
    pytest-cov pytest-ordering flaky pytest-qt pyinstaller pywin32 tornado `
    pip m2w64-toolchain --no-channel-priority

  # Build the extensions.
  - python setup.py build_ext --inplace

build: false

test_script:
  - python runtests.py

after_test:
  - cmd: set PYTHONPATH=C:\projects\gwhat;%PYTHONPATH%
  - cd ./releases
  - pyinstaller.exe gwhat.spec
  - 7z a -tzip ../dist/%GWHAT_VERSION%_win_amd64.zip %GWHAT_VERSION%_win_amd64
  - cd ..

artifacts:
  - path: 'dist/%GWHAT_VERSION%_win_amd64.zip'

on_success:
  - codecov

on_finish:
#   - ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
