# https://ci.appveyor.com/project/jnsebgosselin/WHAT

# scripts that are called at very beginning, before repo cloning
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:

  global:
    PYTHON: "C:\\conda"
    MINICONDA_VERSION: "latest"
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
    PYTHON_ARCH: "64"
    PIP_DEPENDENCIES_FLAGS: "-q"
    CONDA_DEPENDENCIES_FLAGS: "--quiet"
    CONDA_DEPENDENCIES: >
      mock pytest pytest-cov scipy matplotlib
    PIP_DEPENDENCIES: "pytest-qt pytest-mock pytest-timeout pytest-ordering"

  matrix:
    - PYTHON_VERSION: "3.6"

platform:
  -x64

skip_branch_with_pr: true

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "activate test"
  - pip install xlrd
  - pip install xlsxwriter
  - pip install h5py
  - pip install coveralls

build: false

test_script:
  # - "%CMD_IN_ENV% coverage run --source=WHAT --concurrency=thread -m py.test"
  - "%CMD_IN_ENV% python runtests.py"

on_finish:
  - "%CMD_IN_ENV% coveralls"
#   - ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
